#!/usr/bin/env bash
# Script to install and configure Nginx to return "Hello World!" at its root

apt-get update -y
apt-get install -y nginx
service nginx start

echo "Hello World!" > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80;
    server_name _;
    location / {
        root /var/www/html;
        index index.html;
    }
}
EOL

service nginx restart
