#!/usr/bin/env bash
# Script to configure Nginx with a 301 redirection from /redirect_me to another page

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
server_block=$(cat <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF
)
echo "$server_block" | sudo tee /etc/nginx/sites-available/default

sudo nginx -t
if [ $? -eq 0 ]; then
  sudo systemctl restart nginx
else
  echo "Nginx configuration test failed."
  exit 1
fi
